# Generated by Django 3.1.2 on 2020-10-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('prayer', models.CharField(max_length=4096)),
                ('author', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=4096)),
                ('author', models.CharField(max_length=200)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wall.prayer')),
            ],
        ),
    ]
