# Generated by Django 3.1.2 on 2021-07-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='author',
            field=models.CharField(blank=True, default='Anon', max_length=200),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='response',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
