# Generated by Django 3.1.2 on 2021-07-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isDaily',
            field=models.BooleanField(default=False),
        ),
    ]
