# Generated by Django 3.1.2 on 2021-07-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20210729_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='isDaily',
            new_name='isWatch',
        ),
    ]
